spring:
  application:
    name: eureka-service

server:
  port: 8300


eureka:
  client:
    healthcheck:
       enabled: true
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8300/eureka
   

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8301
    user-service:
      path: /user-service/**
      url: http://localhost:8302
    auth-service:
      path: /auth-service/**
      url: http://localhost:8303
      # keeping 'sensitiveHeaders' empty is nacessary for auth-service,
      # as it does not pass "Cookie", "Set-Cookie", "Authorization" headers downstream
      sensitiveHeaders:
